import { Inter } from "next/font/google";
import { Spectral } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const spectral = Spectral({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={spectral.className}>
        <div className="mx-6 md:max-w-7xl md:mx-auto">{children}</div>
      </body>
    </html>
  );
}
